In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.13.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
type(x_train)

numpy.ndarray

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
2+2

4

2+2

In [9]:
x_train.ndim

3

In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.15033102, -1.071599  , -0.42734873, -0.4099252 , -0.05424855,
         0.49426943,  0.18341477, -0.21304412,  0.5546023 , -0.6437207 ]],
      dtype=float32)

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.09171651, 0.03650446, 0.06952488, 0.07074687, 0.10096611,
        0.17474066, 0.12805352, 0.08614133, 0.18560779, 0.05599782]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss_fn(y_train[:1], predictions).numpy()

1.7444524

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2964 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1435 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1106 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0897 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0781 - accuracy: 0.9758


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0774 - accuracy: 0.9764 - 630ms/epoch - 2ms/step


[0.0773661732673645, 0.9764000177383423]