In [9]:
import pandas as pd
import numpy as np

import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.10.0


In [10]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [15]:
type(x_train)

numpy.ndarray

In [22]:
x_train.shape

(60000, 28, 28)

In [19]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [21]:
x_train.ndim

3

In [23]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [24]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.2706923 , -0.00608657, -0.24895805, -0.03251591,  0.05291338,
         0.11714569, -0.251046  , -0.64496756, -0.39467034, -0.77330244]],
      dtype=float32)

In [25]:
tf.nn.softmax(predictions).numpy()

array([[0.15121196, 0.11465226, 0.08993006, 0.11166176, 0.12162027,
        0.12968858, 0.08974248, 0.06052295, 0.07773612, 0.0532335 ]],
      dtype=float32)

In [26]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [27]:
loss_fn(y_train[:1], predictions).numpy()

2.0426192

In [28]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [29]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 874us/step - loss: 0.2888 - accuracy: 0.9163
Epoch 2/5
1875/1875 [==============================] - 2s 834us/step - loss: 0.1410 - accuracy: 0.9588
Epoch 3/5
1875/1875 [==============================] - 2s 844us/step - loss: 0.1069 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 2s 874us/step - loss: 0.0875 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 2s 885us/step - loss: 0.0733 - accuracy: 0.9768


In [30]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0703 - accuracy: 0.9780 - 303ms/epoch - 967us/step


[0.07027536630630493, 0.9779999852180481]