In [16]:
import pandas as pd
import numpy as np

import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.13.0


In [17]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
type(x_train)

numpy.ndarray

In [19]:
x_train.shape

(60000, 28, 28)

In [20]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [21]:
x_train.ndim

3

In [22]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [23]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.0669131 ,  0.60374177, -0.30929214,  0.01226643,  0.34893063,
         0.23252639,  0.46041238, -0.55123526, -0.16348127, -0.2567303 ]],
      dtype=float32)

In [24]:
tf.nn.softmax(predictions).numpy()

array([[0.03313968, 0.17615889, 0.07069342, 0.09750572, 0.13653421,
        0.1215312 , 0.15263616, 0.05550146, 0.08179069, 0.07450858]],
      dtype=float32)

In [25]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [26]:
loss_fn(y_train[:1], predictions).numpy()

2.1075842

In [27]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [28]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.3000 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1451 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1101 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0914 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0783 - accuracy: 0.9755


In [29]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0726 - accuracy: 0.9778 - 1s/epoch - 4ms/step


[0.07262074947357178, 0.9778000116348267]