In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.13.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
type(x_train)

numpy.ndarray

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
x_train.ndim

3

In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.80266273, -0.13860665,  0.10226071,  0.1865326 ,  0.09789006,
        -0.17495246,  0.10465729, -0.04531842, -0.37862605, -0.5597386 ]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.20895323, 0.0815194 , 0.1037214 , 0.11284106, 0.10326906,
        0.07860972, 0.10397027, 0.08949021, 0.0641242 , 0.05350148]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.54326

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2964 - accuracy: 0.9130
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1411 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1043 - accuracy: 0.9688
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0861 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 16s 9ms/step - loss: 0.0725 - accuracy: 0.9768


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 2s - loss: 0.0704 - accuracy: 0.9785 - 2s/epoch - 7ms/step


[0.07040631771087646, 0.9785000085830688]